### ISSUE TITLE
panicked at 'NoopWake cannot wake'

### ISSUE THREAD

**Issue by bbigras** [mehcode/actix-web-async-await#2]
I get that error. I used `futures_util::compat::Compat01As03` to be able to use some futures 0.1 with await!().

Any ideas?

**Comment by mehcode** [comment]
I've only had bad luck with `futures_util::compat` so I would recommend not using it.

Note that `actix_web_async_await::await` works with both futures 0.1 and futures 0.3.

If you need to use compat layers manually grab `tokio-async-await` and look in the compat module.

**Comment by mehcode** [comment]
I'm just re-exporting `await` from that module. So yes, it should be working. If you can share code/errors I might be able to help.

**Comment by bbigras** [comment]
I had the error when I was using the `futures-util-preview` crate with `futures_util::compat` but now it works if I use `into_awaitable()`. I saw that from https://jsdw.me/posts/rust-asyncawait-preview/.

Thanks!
